server:
    port: 8080

spring:
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
    jackson:
        serialization:
            write-dates-as-timestamps: true
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/api?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 
    jpa:
        show-sql: true

management:
    server:
        address: 127.0.0.1
        port: 8081
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true

com:
    mtdhb:
        api:
            third-party-application:
                totals:
                    - 20
                    - 15
                minimums:
                    - 3
                    - 4.5
                dailies:
                    - 3
                    - 5
                patterns:
                    - urlKey=([0-9A-F]{32})
                    - sn=([0-9a-f]{16})
            login-interceptor:
                include-patterns:
                    - "/**"
                exclude-patterns:
                    - /error
                    - /user/login
                    - /user/logout
                    - /user/registerCaptcha
                    - /user/registerMail
                    - /user/register
                    - /user/resetPasswordCaptcha
                    - /user/resetPasswordMail
                    - /user/resetPassword
            nodejs:
                url: http://127.0.0.1:3333
                check-cookie: /check-cookie
                get-hongbao: /get-hongbao
            mail:
                register-mail-subject: 一键领取手气最佳红包-注册
                register-mail-effective-time: 30
                reset-password-mail-subject: 一键领取手气最佳红包-重置密码
                reset-password-mail-effective-time: 30
                blacklist:
                    # http://www.bccto.me/
                    - bccto.me
                    - jnpayy.com
                    - 11163.com
                    - chaichuang.com
                    - a7996.com
                    - dawin.com
                    - 4059.com
                    - 3202.com
                    - 4057.com
                    - ytpayy.com
                    - juyouxi.com
                    - meihuajun76.com
                    - cuirushi.org
                    - zymuying.com
                    - zhaoyuanedu.cn
                    - dhy.cc
                    - cr219.com
                    - mdu.edu.rs
                    - mail.jpgames.net
                    - dongqing365.com
                    - dahongying.net
                    # http://24mail.chacuo.net/
                    - chacuo.net
                    - 027168.com
                    # http://www.yopmail.com/zh/
                    - yopmail.com
                    # https://10minutemail.org/
                    - kpooa.com